spring.application.name=tracker

springdoc.override-with-generic-response=false

spring.datasource.url=jdbc:sqlite:./backend/build/dev-database/tracker.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.mvc.problemdetails.enabled=true

server.address=127.0.0.1
server.port=8080